# ===== PreInit =====

#  Define the level of verbosity of messages
# options: development debugging, trace, routine, warning, error
# default: routine
#/bxlog trace

# Set the event report frequency
# default: 1000
/event/eventreport  1

#Set verbose levels
/bx/physics/verbose  0
#/run/verbose  0

/event/64bit 1

/event/npethreshold 0

# Define  random seed
#/run/heprandomseed 12345679

#Run number being simulated
/bx/detector/run_number 12106

#Detector configuration. Possible choices are: full, fullWater, inWater, inScint, outer, ctf
#Default: full
/bx/detector/configuration full

#PMTs distribution. Possible choices are: real, uniform.
#Default: real
/bx/detector/PMTdistribution real
#Number of PMTs defined only for uniform distribution
#/bx/detector/PMTnumber 2000

#PMT configuration. Possible choices are: diskPMT, diskPMTwithConcentrator, simplePMT
#default: simplePMT
/bx/detector/PMTconfiguration simplePMT

#Setting of NoConcentrators (true=concentrators disabled for any PMT configuration): 
/bx/detector/noConcentrators false

#Vessel's configuration
#/bx/detector/deformed_vessel true
#/bx/detector/vessel_step 1 cm

#Geometry debugging
#/bx/detector/check_overlaps false

#/bx/physics/optical 0
#/bx/detector/nopmts true

#/bx/physics/lightyield 11700

#/bx/physics/new_em 1
#/bx/physics/nuclear 1
#/bx/physics/ionphysics 1
#/run/writeisotopes 1
#/run/writedeposits 1

#/bx/physics/hadronic standard

# Activate decay processes
#/bx/physics/decay 1

# ===== End of PreInit =====

#-----------------------------------
/run/initialize
#-----------------------------------


#===== Generator setup =====

# Define the generator
/bx/generator/select TTree

#Set Tree name
/bx/generator/ttree/tree_name    tree

#Add input ROOT file (full path with extension)
#NOTE: use this command several times to add more than one file. '*' is also supported
/bx/generator/ttree/add_input_file    ~/storage/input_file.root

#Set first TTree(Chain) entry number to be processed
#Default:    0
/bx/generator/ttree/first_entry    0

#Set number of TTree(Chain) entries to be processed
#WARNING! Do NOT change /run/beamOn value from 2^32-1. Use this command instead.
#Default:    all
/bx/generator/ttree/n_entries    10

#Uncomment for change default variables names/values.
#Argument is the variable name in input Tree with unit.
#You can write exact values instead of names/expressions in arguments.
#Then they will be used for all simulated events.
#In this case, such branches in input Tree are not needed.
#It is also possible to mix names and exact values in position, momentum and polarization
#(e.g. /bx/generator/ttree/position    particle.x  particle.y  0.5    m)
#Any expression that is working in TTree::Draw() can be used (even special, like Sum$, see docs of TTree::Draw()).
#WARNING! If there are more than one tokens assumed (as for energy, momentum, position, polarization),
#         DO NOT use whitespaces or tabs inside , because they are tokens separators.
#BONUS: If there are only exact values everywhere in /var/ below,
#       commands /tree_name, /add_input_file above and file(s) with TTree are not needed

#Event id number
#WARNING! Do not use exact number here!
#Default: Tree(Chain) entry number
#/bx/generator/ttree/var/event_id    iev

#Skip event if condition (boolean expression) is true.
#Example: skip event if particles PDG array contains mu- or mu+:
#         /event_skip_if    Sum$(p.pdg==13 || p.pdg==-13) > 0
#Default:    0
#/bx/generator/ttree/var/event_skip_if    event_condition

#Skip particle if condition (boolean expression) is true.
#Example: skip event if particle is mu- or mu+:
#         /event_skip_if    p.pdg==13 || p.pdg==-13
#Default:    0
#/bx/generator/ttree/var/particle_skip_if    particle_condition

#Number of particles per Tree entry
#Default:    1
#/bx/generator/ttree/var/n_particles    n

#Split particles to separate events.
#NOTE: When true, particles within one TTree(Chain) entry will be simulated as separate Geant events
       and written into separate BX events, but with same MCTruth EventID
#NOTE: As exact values use only 0/1, true/false will be interpreted as branch name.
#Default:    0
#/bx/generator/ttree/var/split    1

#Rotate particles directions to a random angle in 3D
#Can be used to obtain isotropic particle source when all 3 components in Momentum/direction are exact values,
e.g. like default  0 0 1  MeV.
#NOTE: As exact values use only 0/1, true/false will be interpreted as branch name.
#NOTE: All particles from single Tree entry are rotated by the same angle
#WARNING: Do not use it, having multiple particles with different(!) positions in single Tree entry!
          It rotates only directions, positions remains the same.
          Let's consider two particles on plain:
              1*-->    <--*2
          Potating their directions by Pi we will have
              <--*1    2*-->
          which is obviously not the same with rotating the whole system
              2*-->    <--*1
          So it is safe only when all particles in single Tree entry have the same position
#Default:    0
/bx/generator/ttree/var/rotate_iso    0

#PDG code of particle
#Default: 22
#/bx/generator/ttree/var/pdg    pdg

#Kinetic energy
#Note: see Momentum/direction
#Default:    1    MeV
#/bx/generator/ttree/var/Ekin    E    MeV

#Momentum/direction
#NOTE: if value of Ekin < 0 (in mac-file or/and in input TTree), (px,py,pz)-vector is used as 3-momentum vector.
#      Otherwise (px,py,pz)-vector is normalized and used as direction vector.
#Default:    0 0 1    MeV
#/bx/generator/ttree/var/momentum    px py pz    MeV

#Vertex position
#Default:    0 0 0    m
#/bx/generator/ttree/var/position    x y z    m

#Vertex time
#Default:    0    ns
#/bx/generator/ttree/var/time    t    ns

#Particle polarization
#Default: none
#/bx/generator/ttree/var/polz    polz_x polz_y polz_z


#Event postponing (stacking)
#/bx/stack/select    TTree

#Turn on mode for stacking
#NOTE: possible arguments are 'all', or any space separated combination of 'neutron', 'muon' and 'ra_decay'
#Default: none
#/bx/stack/ttree/mode    all

# ===== End of Generator setup =====


# Define output file name
/run/filename BxGeneratorTTree_test

#WARNING! DO NOT EDIT ! G4int max for 32bit: 2^32-1
#         Use /bx/generator/ttree/n_entries command instead.
/run/beamOn 2147483647
